### ISSUE TITLE
Empty text nodes seem to cause problems in isomorphic Miso

### ISSUE THREAD

**Issue by niteria** [dmjio/miso#589]
**Describe the bug**
I have an example where changing `""` to `" "` makes a difference between the app working and a crash in a browser.

Here's a crashing version: https://github.com/niteria/miso-isomorphic-example/commit/a22975c537e9edd9ca4b236d3ee132c4340f3c06
Here's a patch that makes it work: https://github.com/niteria/miso-isomorphic-example/commit/22ebdaa47d0830a0131afa1130557f273e60d656

**To Reproduce**
```
git clone https://github.com/niteria/miso-isomorphic-example && cd miso-isomorphic-example
git checkout empty-text-node-problem
(cd $(nix-build) && bin/server)
# look at localhost:3003 in the browser
# click the "+" button
# the app stops responding after that and there's an error in the browser console
```

Browser console output:
```
uncaught exception in Haskell main thread: TypeError: b.domRef is undefined all.js:215:83
window.diffTextNodes@http://localhost:3003/static/all.js:680:342
window.diff@http://localhost:3003/static/all.js:679:180
window.diffChildren@http://localhost:3003/static/all.js:684:400
window.populate@http://localhost:3003/static/all.js:682:174
window.diffVNodes@http://localhost:3003/static/all.js:682:313
window.diff@http://localhost:3003/static/all.js:679:223
window.diffChildren@http://localhost:3003/static/all.js:684:400
window.populate@http://localhost:3003/static/all.js:682:174
window.diffVNodes@http://localhost:3003/static/all.js:682:313
window.diff@http://localhost:3003/static/all.js:679:223
h$$aaW@http://localhost:3003/static/all.js:1878:96
h$runThreadSlice@http://localhost:3003/static/all.js:255:213
h$runThreadSliceCatch@http://localhost:3003/static/all.js:254:46
h$mainLoop@http://localhost:3003/static/all.js:253:163
h$mkForeignCallback/<@http://localhost:3003/static/all.js:275:238
all.js:215:83
uncaught exception: Thread aborted, exit code: 0 all.js:268:401
```

**Expected behavior**
No crash.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 76.0.1

**Additional context**
This is a minimized example from a problem I run into in a real app. It's not doing anything interesting.

**Comment by niteria** [comment]
I worked around the problem in my app by using `"\8204"` instead of `""`. That's https://en.wikipedia.org/wiki/Zero-width_non-joiner.

**Comment by dmjio** [comment]
Yea, the issue here being that the browsers HTML parser cannot distinguish between multiple sibling text nodes and a single text node. It will collapse sibling text nodes into a single text node causing copyDOMIntoVTree to fallback to redrawing the entire view. There is a way to attempt to recreate the DOM as miso sees it and then perform the copy, but it is in a separate branch.

**Comment by niteria** [comment]
Is there an empty `View action`? One that renders to nothing?

Then I could have:
```
text' t 
 | null t = empty
 | otherwise = text t
```

**Comment by dmjio** [comment]
`empty :: View action = text mempty` would be the closest thing. But this will not render nothing, it will call `document.createTextNode ('')`

**Comment by dmjio** [comment]
@niteria, thought of an idea to fix this. Before rendering the virtual DOM to the actual DOM, we can have a preprocessing step that collapses all sibling text nodes. We could do this on the server as well just to be consistent. This would solve the problem at the cost of some speed, I believe.

```
div_ [ ] [ text "foo", text "", text " ", text "bar" ]
```
becomes

```
div_ [ ] [ text "foo bar" ]
```

**Comment by niteria** [comment]
Makes sense to me.

**Comment by dmjio** [comment]
@niteria would you care to test your changes against this [PR](https://github.com/dmjio/miso/pull/591) ? Would be very helpful for review.

**Comment by niteria** [comment]
Just tested, your PR fixes the issue, the app works and no errors in the console.

**Comment by dmjio** [comment]
Wow, that's wild. Incredible news.

**Comment by dmjio** [comment]
@niteria just to humor me, can you confirm that when the HTML differs, it doesn't crash, but falls back to redrawing from scratch.

**Comment by dmjio** [comment]
After this I think we can merge.

**Comment by niteria** [comment]
I may not get to this today. In case you want to test it sooner, changing the version of miso that the reproducer uses is as easy as editing those two lines https://github.com/niteria/miso-isomorphic-example/blob/empty-text-node-problem/nixpkgs.nix#L8-L9

**Comment by niteria** [comment]
I used the `Show URI` instance to produce the differences between server and client on this branch https://github.com/niteria/miso-isomorphic-example/tree/empty-text-node-problem-test-pr-591 and unfortunately it fails.

If I press the `+` button nothing happens, and the `-` button throws:

```
uncaught exception in Haskell main thread: TypeError: b.domRef is undefined all.js:215:83
window.diffTextNodes@http://localhost:3003/static/all.js:680:342
window.diff@http://localhost:3003/static/all.js:679:180
window.diffChildren@http://localhost:3003/static/all.js:684:400
window.populate@http://localhost:3003/static/all.js:682:174
window.diffVNodes@http://localhost:3003/static/all.js:682:313
window.diff@http://localhost:3003/static/all.js:679:223
window.diffChildren@http://localhost:3003/static/all.js:684:400
window.populate@http://localhost:3003/static/all.js:682:174
window.diffVNodes@http://localhost:3003/static/all.js:682:313
window.diff@http://localhost:3003/static/all.js:679:223
h$$aaV@http://localhost:3003/static/all.js:1877:340
h$runThreadSlice@http://localhost:3003/static/all.js:255:213
h$runThreadSliceCatch@http://localhost:3003/static/all.js:254:46
h$mainLoop@http://localhost:3003/static/all.js:253:163
h$mkForeignCallback/<@http://localhost:3003/static/all.js:275:238
```

**Comment by dmjio** [comment]
To confirm you are using the `miso` function and not `startApp`

**Comment by niteria** [comment]
Sure https://github.com/niteria/miso-isomorphic-example/blob/a927906919c549c36cd36fd6dfad0a6127f387aa/client/Main.hs#L21

**Comment by dmjio** [comment]
It should be hitting this line and falling back to a full redraw https://github.com/dmjio/miso/blob/master/jsbits/isomorphic.js#L5

It seems like the copy is silently failing, and then in subsequent diffs the orphaned nodes are referenced.

**Comment by dmjio** [comment]
@niteria to confirm, you never see this printing to the console.
```js    console.warn('Could not copy DOM into virtual DOM, falling back to diff');```

**Comment by niteria** [comment]
Correct, that never appears.

**Comment by dmjio** [comment]
@niteria I believe I found the issue.

1) If the DOM node being walked is undefined, we should prematurely exit. This led to bad bugs in the console.

2) If the DOM node and VDOM differ, we should diff from the `node.parentNode`, not the `node`.

https://github.com/dmjio/miso/pull/591/files#diff-d5e8e95fc1986e4d2b3b8f9714f57092R21

I think it should work now.

**Comment by niteria** [comment]
I rerun it https://github.com/dmjio/miso/commit/936ce48eb8ec33024de8c5ea8d1832654a41e595 and I still get the same behavior as https://github.com/dmjio/miso/issues/589#issuecomment-643344205.

Here's the commit if you want to run it yourself https://github.com/niteria/miso-isomorphic-example/commit/2acef35b2aa97311cedb8e69ac2191347e79e0ed

**Comment by niteria** [comment]
This change makes the fallback "work" for me: https://github.com/niteria/miso/commit/36a0f00a75d21e47d3cd94ccb804de306b07aec7

I say "work" because I get the fallback message. Unfortunately the old DOM is no removed so I get this:

![Screenshot_20200613_223251](https://user-images.githubusercontent.com/212146/84578475-d6ac4c80-adc5-11ea-8353-5bd8f0766ff5.png)

**Comment by dmjio** [comment]
@niteria, sorry I forgot to add back the code that does the `domRef` copying, hence why we see `undefined`s.

```javascript
 vdomChild['domRef'] = domChild;
```

**Comment by niteria** [comment]
These two changes on top of your work make it work perfectly for me https://github.com/dmjio/miso/compare/collapse-siblings...niteria:collapse-siblings

**Comment by dmjio** [comment]
@niteria Nice, I've added your changes, and incorporated some error logging, `diagnoseError`, to log when the `vdomChild` and `domChild` aren't the same. Hopefully this will be more helpful to users.

**Comment by niteria** [comment]
![Screenshot_20200613_234141](https://user-images.githubusercontent.com/212146/84579620-74584980-adcf-11ea-92ba-c400e2658794.png)

Awesome, that covers #588 as well.

**Comment by dmjio** [comment]
Sweet, I think we should add a `debug :: Bool` to the `App` constructor to top this off. This way users can hide these notifications. Sound good?

**Comment by dmjio** [comment]
This is technically the pinnacle of `miso` (play on isomorphic), so best to get it right, and be able to debug when its not :)

**Comment by niteria** [comment]
Works for me. On the other hand, the "falling back to diff" message is printed unconditionally when there's a difference, so I wouldn't mind the same happening with the "VTree differed..." message.

**Comment by dmjio** [comment]
Will add this as well. Technically, we no longer need the `startApp` function, since `miso` can handle it all.

**Comment by dmjio** [comment]
#591
